#DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
   # schema: classpath:db/schema-h2.sql
   # data: classpath:db/data-h2.sql
    url: jdbc:mysql://localhost:3306/jdbase?characterEncoding=utf8&useUnicode=true&serverTimezone=Asia/Shanghai
    username: test
    password: 123456


#mybatis-plus:
#  configuration:
